### ISSUE TITLE
Compilation from within Eclipse not working on Linux Ubuntu

### ISSUE THREAD

**Issue by RBirdwatcher** [eclipse/efbt#714]

**Comment by RBirdwatcher** [comment]
when launching app from within eclipse on ubuntu we can launch, but when we look at a logical transformation diagram we get the following stack trace:

!ENTRY org.eclipse.ui 4 0 2021-11-18 10:42:07.227
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/java.awt.Cursor.<clinit>(Cursor.java:185)
	at org.apache.batik.bridge.CursorManager.<clinit>(Unknown Source)
	at org.apache.batik.bridge.BridgeContext.<init>(Unknown Source)
	at org.apache.batik.bridge.BridgeContext.<init>(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.createBridgeContext(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.eclipse.sirius.diagram.ui.tools.internal.figure.svg.SimpleImageTranscoder.transcode(SimpleImageTranscoder.java:106)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.eclipse.sirius.diagram.ui.tools.internal.figure.svg.SimpleImageTranscoder.updateImage(SimpleImageTranscoder.java:164)
	at org.eclipse.sirius.diagram.ui.tools.internal.figure.svg.SimpleImageTranscoder.getBufferedImage(SimpleImageTranscoder.java:181)
	at org.eclipse.sirius.diagram.ui.tools.internal.figure.svg.SimpleImageTranscoder.getAspectRatio(SimpleImageTranscoder.java:90)
	at org.eclipse.sirius.diagram.ui.tools.api.figure.SVGFigure.contentChanged(SVGFigure.java:353)
	at org.eclipse.sirius.diagram.ui.tools.api.figure.SVGWorkspaceImageFigure.flyWeightImage(SVGWorkspaceImageFigure.java:178)
	at org.eclipse.sirius.diagram.ui.tools.api.figure.WorkspaceImageFigure.getImageInstanceFromPath(WorkspaceImageFigure.java:199)
	at org.eclipse.sirius.diagram.ui.edit.internal.part.AbstractDiagramNodeEditPartRefreshVisualsOperation.refreshWidth(AbstractDiagramNodeEditPartRefreshVisualsOperation.java:178)
	at org.eclipse.sirius.diagram.ui.edit.internal.part.AbstractDiagramNodeEditPartRefreshVisualsOperation.refreshSize(AbstractDiagramNodeEditPartRefreshVisualsOperation.java:95)
	at org.eclipse.sirius.diagram.ui.edit.internal.part.DiagramNodeEditPartOperation.internalRefreshVisuals(DiagramNodeEditPartOperation.java:107)
	at org.eclipse.sirius.diagram.ui.edit.internal.part.DiagramNodeEditPartOperation.refreshVisuals(DiagramNodeEditPartOperation.java:75)
	at org.eclipse.sirius.diagram.ui.edit.api.part.AbstractDiagramNodeEditPart.refreshVisuals(AbstractDiagramNodeEditPart.java:282)

**Comment by RBirdwatcher** [comment]
This can be resolved by making sure that things we set the jare to be used as the justJ jre.
This can be done on windows->preferences, Need to update the instructions for installing a dev environment to specify this .
